### ISSUE TITLE
difference between website and PHP example

### ISSUE THREAD

**Issue by asiOnTheWater** [danmandle/JSON2CSV#3]
would love to leverage the tool but I'm having issues with the php example. The website solution is able to convert the json below but the PHP script isn't. Any help would be greatly appreciated

**Comment by danmandle** [comment]
Hi Asi, the code on the website is exactly the same as that in the repo. How are you loading the JSON into the script? It may be an issue between Mac in Linux line endings.

On a side note, which SendGrid office do you work for? I know a few people who work for SendGrid here in Boulder.

**Comment by asiOnTheWater** [comment]
I actually work in the Anaheim, CA office but visit both offices in CO :) Who do u happen to know from SendGrid?

this is the way I’m exe the php script (php json2csv.php --file=page1.json)

*sorry for the long json, I thought I truncated it before posting :( I just updated it so it doesn’t eat up landscape 
With Kind Regards, 

Anthony S.

Senior Technical Support Engineer

On April 8, 2014 at 7:49:38 AM, Dan Mandle (notifications@github.com) wrote:

Hi Asi, the code on the website is exactly the same as that in the repo. How are you loading the JSON into the script? It may be an issue between Mac in Linux line endings.

On a side note, which SendGrid office do you work for? I know a few people who work for SendGrid here in Boulder.

**Comment by danmandle** [comment]
What kind of errors is it generating? Again, my initial guess is that it has something to do with the line endings.

**Comment by asiOnTheWater** [comment]
Below is what is what I am getting consistently, I’ll try to mess around  and see what works. Thanks for looking into this

Array to string conversion in /Users/anthonysi/Downloads/JSON2CSV-master/json2csv.class.php on line 34
With Kind Regards, 

Anthony S.

Senior Technical Support Engineer

On April 8, 2014 at 8:03:17 AM, Dan Mandle (notifications@github.com) wrote:

What kind of errors is it generating? Again, my initial guess is that it has something to do with the line endings.

**Comment by danmandle** [comment]
The problem is that the JSON has nested elements. The script doesn't handle nested elements yet. You said that this worked on my hosted version?

**Comment by asiOnTheWater** [comment]
it certainly does. I can send you the file that was DL if you would like

**Comment by danmandle** [comment]
Let's take this offline. You can email me at dan at mandle dot me.
