### ISSUE TITLE
Getting errors when converting

### ISSUE THREAD

**Issue by pyretta** [danmandle/JSON2CSV#6]
Hello,
I tried your code to convert a very huge JSON file into a CSV, but I only get these following error messages in the exported CSV file:

Warning:  array_keys() expects parameter 1 to be array, null given in D:\XAMPP\htdocs\www\JSON2CSV\json2csv.class.php on line 21
Warning:  Invalid argument supplied for foreach() in D:\XAMPP\htdocs\www\JSON2CSV\json2csv.class.php on line 21
Notice:  Undefined variable: keys in D:\XAMPP\htdocs\www\JSON2CSV\json2csv.class.php on line 24
Warning:  array_merge(): Argument #1 is not an array in D:\XAMPP\htdocs\www\JSON2CSV\json2csv.class.php on line 24
Warning:  Invalid argument supplied for foreach() in D:\XAMPP\htdocs\www\JSON2CSV\json2csv.class.php on line 73

The used JSON file seemed to be valid, as JSONlint says.

Can you help me fix this?
Thank you very much in advance.

Best regards,
pyretta

**Comment by danmandle** [comment]
I believe the issue is that your JSON is not an array.

**Comment by pyretta** [comment]
Ok. This could be. This is how my JSON file looks like:

{
  "Arg1": "some value",
  "Arg2": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.",  
  "Arg3": {
    "Arg3_1": "some value",
    "Arg3_2": "some value",
    "Arg3_3": "some value"
  }
}

**Comment by danmandle** [comment]
Yup, those are objects with no arrays.

**Comment by pyretta** [comment]
So there is no way to convert this?

**Comment by danmandle** [comment]
Not in the JSON's present form. You will have to change the way the JSON is formatted or figure out another way of doing the CSV conversion. I am available for hire if you need more help.
