### ISSUE TITLE
can you make it more json instagram friendly ?! 

### ISSUE THREAD

**Issue by minanagehsalalma** [danmandle/JSON2CSV#8]
https://superuser.com/questions/1412477/how-can-i-view-my-instagram-backup-data-in-a-friendly-way

**Comment by danmandle** [comment]
No. This tool takes json arrays and converts them into CSV rows. It's universal and standardized.

**Comment by minanagehsalalma** [comment]
Oh ... thanks ...
If you  have any ideas please let me know .

**Comment by danmandle** [comment]
You will need a programmer to do that. I am available for hire.

**Comment by minanagehsalalma** [comment]
@danmandle  lol..... how much for this job ?

**Comment by danmandle** [comment]
Reach out to me directly at firstname@lastname.me (break apart my username)
